"""add subject123 to teacher

Revision ID: 2a20ce61505b
Revises: 2a0f1d0eee60
Create Date: 2026-05-05 15:53:56.455115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a20ce61505b'
down_revision: Union[str, Sequence[str], None] = '2a0f1d0eee60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Department',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('dept_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('dept_id')
    )
    op.create_index(op.f('ix_Department_dept_id'), 'Department', ['dept_id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('mail', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('dept', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Student_id'), 'Student', ['id'], unique=False)
    op.create_table('Teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=15), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('hod_dept_id', sa.Integer(), nullable=True),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['Department.dept_id'], ),
    sa.ForeignKeyConstraint(['hod_dept_id'], ['Department.dept_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Teacher_id'), 'Teacher', ['id'], unique=False)
    op.create_table('Course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('incharge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incharge_id'], ['Teacher.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Course_id'), 'Course', ['id'], unique=False)
    op.drop_index(op.f('ix_Course_id'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('email'), table_name='teacher')
    op.drop_index(op.f('ix_Teacher_id'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('email'), table_name='student')
    op.drop_index(op.f('ix_Student_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_Department_dept_id'), table_name='department')
    op.drop_table('department')
    op.drop_constraint(op.f('session_ibfk_1'), 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'User', ['user_id'], ['id'])
    op.drop_constraint(op.f('student_course_ibfk_2'), 'student_course', type_='foreignkey')
    op.drop_constraint(op.f('student_course_ibfk_1'), 'student_course', type_='foreignkey')
    op.create_foreign_key(None, 'student_course', 'Student', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_course', 'Course', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('teacher_course_ibfk_1'), 'teacher_course', type_='foreignkey')
    op.drop_constraint(op.f('teacher_course_ibfk_2'), 'teacher_course', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_course', 'Teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher_course', 'Course', ['course_id'], ['id'], ondelete='CASCADE')
    op.add_column('token', sa.Column('access_token12', sa.String(length=450), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'access_token12')
    op.drop_constraint(None, 'teacher_course', type_='foreignkey')
    op.drop_constraint(None, 'teacher_course', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_course_ibfk_2'), 'teacher_course', 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('teacher_course_ibfk_1'), 'teacher_course', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'student_course', type_='foreignkey')
    op.drop_constraint(None, 'student_course', type_='foreignkey')
    op.create_foreign_key(op.f('student_course_ibfk_1'), 'student_course', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_course_ibfk_2'), 'student_course', 'student', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key(op.f('session_ibfk_1'), 'session', 'user', ['user_id'], ['id'])
    op.create_table('department',
    sa.Column('dept_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('dept_name', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('dept_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Department_dept_id'), 'department', ['dept_id'], unique=False)
    op.create_table('student',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('lastname', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('semester', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('dept', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contact', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('start_date', mysql.DATETIME(), nullable=True),
    sa.Column('end_date', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('student_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Student_id'), 'student', ['id'], unique=False)
    op.create_index(op.f('email'), 'student', ['email'], unique=True)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('mail', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 'user', ['username'], unique=True)
    op.create_table('teacher',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contact', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('dept_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hod_dept_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('joined_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['department.dept_id'], name=op.f('teacher_ibfk_1')),
    sa.ForeignKeyConstraint(['hod_dept_id'], ['department.dept_id'], name=op.f('teacher_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('teacher_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Teacher_id'), 'teacher', ['id'], unique=False)
    op.create_index(op.f('email'), 'teacher', ['email'], unique=True)
    op.create_table('course',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('incharge_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['incharge_id'], ['teacher.id'], name=op.f('course_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Course_id'), 'course', ['id'], unique=False)
    op.drop_index(op.f('ix_Course_id'), table_name='Course')
    op.drop_table('Course')
    op.drop_index(op.f('ix_Teacher_id'), table_name='Teacher')
    op.drop_table('Teacher')
    op.drop_index(op.f('ix_Student_id'), table_name='Student')
    op.drop_table('Student')
    op.drop_table('User')
    op.drop_index(op.f('ix_Department_dept_id'), table_name='Department')
    op.drop_table('Department')
    # ### end Alembic commands ###
